import { Card, CardContent } from "@/components/ui/card";
import { EMVReference } from "@/components/EMVReference";
import { ExternalLink } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { emvData } from "@/lib/emv-data";
import { MainLayout } from "@/components/MainLayout";

export default function EMVReferencePage() {
  return (
    <MainLayout>
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">EMV Reference Guide</h1>
        <p className="mt-2 text-gray-600">
          Comprehensive guide to understanding Earned Media Value calculations and factors
        </p>
      </div>

      <div className="space-y-6">
        <Card>
          <CardContent className="pt-6">
            <div className="prose max-w-none">
              <h2 className="text-2xl font-bold mb-4">What is Earned Media Value (EMV)?</h2>
              <p className="text-gray-700 mb-6">
                Earned Media Value (EMV) is a metric used to quantify the monetary worth of organic social media engagement. 
                It helps brands understand the value generated by influencer partnerships and social media content by translating 
                engagement metrics into dollar amounts that would be equivalent to paid advertising spend.
              </p>

              <h3 className="text-xl font-semibold mb-3">How EMV is Calculated</h3>
              <p className="text-gray-700 mb-4">
                Our EMV calculation uses a sophisticated formula that considers multiple factors:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-700 mb-6">
                <li><strong>Base Engagement Values:</strong> Different engagement types have different monetary values</li>
                <li><strong>Platform Multipliers:</strong> Each social platform has unique audience behaviors and reach</li>
                <li><strong>Creator Size Factors:</strong> Audience size affects engagement quality and reach</li>
                <li><strong>Content Topic Factors:</strong> Certain content categories generate higher engagement rates</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <h3 className="text-xl font-semibold mb-4">Platform-Specific Factors</h3>
            <Accordion type="single" collapsible className="w-full">
              {Object.entries(emvData.platformFactors).map(([platform, factor]) => (
                <AccordionItem key={platform} value={platform}>
                  <AccordionTrigger className="capitalize">
                    {platform} (Factor: {factor}x)
                  </AccordionTrigger>
                  <AccordionContent>
                    <div className="space-y-2">
                      <p>Platform multiplier: <strong>{factor}x</strong></p>
                      <p className="text-sm text-gray-600">
                        This factor is applied to the base EMV calculation to account for 
                        platform-specific audience behavior and engagement patterns.
                      </p>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <h3 className="text-xl font-semibold mb-4">Creator Size Categories</h3>
            <Accordion type="single" collapsible className="w-full">
              {Object.entries(emvData.creatorFactors).map(([size, factor]) => (
                <AccordionItem key={size} value={size}>
                  <AccordionTrigger>
                    {size} (Factor: {factor}x)
                  </AccordionTrigger>
                  <AccordionContent>
                    <div className="space-y-2">
                      <p>Creator size multiplier: <strong>{factor}x</strong></p>
                      <p className="text-sm text-gray-600">
                        Different creator sizes have varying levels of audience engagement and influence, 
                        which is reflected in this multiplier.
                      </p>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <h3 className="text-xl font-semibold mb-4">Content Topic Factors</h3>
            <Accordion type="single" collapsible className="w-full">
              {Object.entries(emvData.topicFactors).map(([topic, factor]) => (
                <AccordionItem key={topic} value={topic}>
                  <AccordionTrigger className="capitalize">
                    {topic} (Factor: {factor}x)
                  </AccordionTrigger>
                  <AccordionContent>
                    <div className="space-y-2">
                      <p>Topic multiplier: <strong>{factor}x</strong></p>
                      <p className="text-sm text-gray-600">
                        Content topics perform differently across platforms, with some categories 
                        generating higher engagement rates and commercial value.
                      </p>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <h3 className="text-xl font-semibold mb-4">Base Engagement Values by Platform</h3>
            <div className="space-y-4">
              {Object.entries(emvData.baseValues).map(([platform, postTypes]) => (
                <div key={platform} className="border rounded-lg p-4">
                  <h4 className="font-semibold capitalize mb-3 text-lg">{platform}</h4>
                  {Object.entries(postTypes).map(([postType, engagements]) => (
                    <div key={postType} className="mb-4">
                      <h5 className="font-medium capitalize mb-2 text-gray-700">{postType}</h5>
                      <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
                        {Object.entries(engagements).map(([engagement, value]) => (
                          <div key={engagement} className="text-sm p-2 bg-gray-50 rounded">
                            <span className="font-medium capitalize">{engagement}:</span>
                            <span className="text-primary-600 font-semibold ml-1">${value}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <h3 className="text-xl font-semibold mb-4">Best Practices</h3>
            <div className="space-y-4">
              <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                <h4 className="font-semibold text-blue-900 mb-2">Data Accuracy</h4>
                <p className="text-blue-800 text-sm">
                  Ensure all engagement metrics are accurately reported and up-to-date for the most reliable EMV calculations.
                </p>
              </div>
              <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
                <h4 className="font-semibold text-green-900 mb-2">Regular Updates</h4>
                <p className="text-green-800 text-sm">
                  EMV factors and base values are periodically updated to reflect current market conditions and platform changes.
                </p>
              </div>
              <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
                <h4 className="font-semibold text-yellow-900 mb-2">Context Matters</h4>
                <p className="text-yellow-800 text-sm">
                  Consider campaign objectives, target audience, and brand alignment when interpreting EMV results.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </MainLayout>
  );
}